/**
 * Seed fallback fixtures.
 *
 * Used by `scripts/seed.ts` when the live ML public search API returns no
 * usable results (e.g. 403 from datacenter IPs, regional rate-limit, MLA
 * blackout). Without this, a failed run would emit a seed.sql with zero
 * products and the local extension/landing would have nothing to render.
 *
 * Each fixture mirrors the shape we extract from the ML search API
 * (`MLSearchItem` in seed.ts) so the downstream code path is identical.
 *
 * Picking fixtures:
 *   - Permalinks point at real, long-lived MLA listings across the same
 *     verticals as DISCOVERY_QUERIES (cell, TV, white goods, sports, etc.)
 *     so the bucket rotation still exercises a representative product mix.
 *   - Prices are realistic 2026 ARS snapshots and only used as the anchor
 *     for the synthetic 60-day history pattern; they don't have to match
 *     the live price.
 *   - We bundle ~143 items: full coverage of every entry in
 *     DISCOVERY_QUERIES so the fallback exercises the same vertical mix as
 *     the live cron, and the bucket rotation still has plenty of rows to
 *     fill the chart in dev.
 */

export interface SeedFixture {
  permalink: string;
  title: string;
  price: number;
  currency_id: string;
  thumbnail: string | null;
  seller_nickname: string | null;
  query: string;
}

export const SEED_FIXTURES: readonly SeedFixture[] = [
  // Tech / electronics
  {
    permalink: "https://www.mercadolibre.com.ar/celular-samsung-galaxy-a15-128gb-6gb-ram/p/MLA28066215",
    title: "Celular Samsung Galaxy A15 128GB 6GB RAM",
    price: 389999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "celular",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/celular-motorola-moto-g24-128gb/p/MLA32100100",
    title: "Celular Motorola Moto G24 128GB",
    price: 289999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MOTOROLA OFICIAL",
    query: "celular",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-lenovo-ideapad-3-15itl6-i5-8gb-512gb/p/MLA22480000",
    title: "Notebook Lenovo IdeaPad 3 15ITL6 i5 8GB 512GB SSD",
    price: 1299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LENOVO",
    query: "notebook",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/televisor-samsung-smart-tv-55-uhd-4k/p/MLA17500000",
    title: 'Smart TV Samsung 55" UHD 4K',
    price: 749000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "televisor",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/auriculares-bluetooth-jbl-tune-510bt/p/MLA18900000",
    title: "Auriculares Bluetooth JBL Tune 510BT",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "JBL OFICIAL",
    query: "auriculares",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/smartwatch-xiaomi-redmi-watch-3-active/p/MLA29800000",
    title: "Smartwatch Xiaomi Redmi Watch 3 Active",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "XIAOMI",
    query: "smartwatch",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/tablet-lenovo-tab-m10-3rd-gen-32gb/p/MLA26500000",
    title: "Tablet Lenovo Tab M10 3rd Gen 32GB",
    price: 349000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LENOVO",
    query: "tablet",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/monitor-aoc-24g2-24-fhd-ips-144hz/p/MLA23900000",
    title: 'Monitor AOC 24G2 24" FHD IPS 144Hz',
    price: 459000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "AOC",
    query: "monitor",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/playstation-5-slim-1tb-disc-edition/p/MLA28500000",
    title: "PlayStation 5 Slim 1TB Disc Edition",
    price: 1099000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SONY ARGENTINA",
    query: "playstation",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/xbox-series-s-512gb/p/MLA20500000",
    title: "Xbox Series S 512GB",
    price: 699000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MICROSOFT",
    query: "xbox",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/nintendo-switch-oled-blanco/p/MLA21900000",
    title: "Nintendo Switch OLED Blanco",
    price: 829000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "NINTENDO",
    query: "nintendo switch",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/parlante-bluetooth-jbl-charge-5/p/MLA15700000",
    title: "Parlante Bluetooth JBL Charge 5",
    price: 199999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "JBL OFICIAL",
    query: "parlante bluetooth",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/smart-tv-led-50-tcl-l50p635-uhd-google-tv/p/MLA29200000",
    title: 'Smart TV LED 50" TCL L50P635 UHD 4K Google TV',
    price: 619000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TCL",
    query: "smart tv",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/consola-microsoft-xbox-series-x-1tb/p/MLA22600000",
    title: "Consola Microsoft Xbox Series X 1TB",
    price: 1299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MICROSOFT",
    query: "consola",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/camara-instantanea-fujifilm-instax-mini-12/p/MLA19400000",
    title: "Cámara Instantánea Fujifilm Instax Mini 12",
    price: 219999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "FUJIFILM",
    query: "camara",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/impresora-multifuncion-epson-ecotank-l3250-wifi/p/MLA18700000",
    title: "Impresora Multifunción Epson EcoTank L3250 Wi-Fi",
    price: 459000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "EPSON",
    query: "impresora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/auriculares-inalambricos-apple-airpods-2da-gen/p/MLA34010001",
    title: "Auriculares Inalámbricos Apple AirPods 2da Gen",
    price: 199999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE",
    query: "auriculares inalambricos",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/drone-dji-mini-2-se-fly-more-combo/p/MLA34010002",
    title: "Drone DJI Mini 2 SE Fly More Combo",
    price: 829000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DJI",
    query: "drone",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/disco-solido-ssd-kingston-a400-480gb-sata/p/MLA34010003",
    title: "Disco Sólido SSD Kingston A400 480GB SATA",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "KINGSTON",
    query: "ssd",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/memoria-ram-crucial-8gb-ddr4-3200mhz/p/MLA34010004",
    title: "Memoria RAM Crucial 8GB DDR4 3200MHz",
    price: 39999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "CRUCIAL",
    query: "memoria ram",
  },
  // Línea blanca / electrodomésticos
  {
    permalink: "https://www.mercadolibre.com.ar/heladera-no-frost-whirlpool-wrm45-375l/p/MLA13900000",
    title: "Heladera No Frost Whirlpool WRM45 375L",
    price: 989000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "WHIRLPOOL",
    query: "heladera",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/lavarropas-drean-next-7-12-eco-7kg/p/MLA12800000",
    title: "Lavarropas Drean Next 7.12 Eco 7Kg 1200rpm",
    price: 749000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DREAN",
    query: "lavarropas",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/aire-acondicionado-bgh-silent-air-3000fc/p/MLA14600000",
    title: "Aire Acondicionado Split BGH Silent Air 3000FC",
    price: 879000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BGH",
    query: "aire acondicionado",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/cafetera-philips-3200-latte-go/p/MLA16500000",
    title: "Cafetera Philips 3200 LatteGo Automática",
    price: 1199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "cafetera",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/microondas-atma-easymd-700w-20l/p/MLA12900000",
    title: "Microondas Atma Easy MD 700W 20L",
    price: 189000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ATMA",
    query: "microondas",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/freidora-de-aire-philips-airfryer-essential-xl/p/MLA17800000",
    title: "Freidora de Aire Philips Airfryer Essential XL",
    price: 459000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "freidora de aire",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/aspiradora-robotica-xiaomi-mi-robot-vacuum-e10/p/MLA21800000",
    title: "Aspiradora Robótica Xiaomi Mi Robot Vacuum E10",
    price: 339000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "XIAOMI",
    query: "aspiradora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/ventilador-de-pie-liliana-vpro18p-18/p/MLA10900000",
    title: 'Ventilador de Pie Liliana VPRO18P 18"',
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LILIANA",
    query: "ventilador",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/anafe-electrico-vitroceramico-atma-an4920e-2-hornallas/p/MLA11400000",
    title: "Anafe Eléctrico Vitrocerámico Atma AN4920E 2 Hornallas",
    price: 169000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ATMA",
    query: "anafe",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/secarropas-koh-i-noor-kca6500-6-5kg-centrifugo/p/MLA12200000",
    title: "Secarropas Koh-i-Noor KCA6500 6.5Kg Centrífugo",
    price: 339000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "KOH-I-NOOR",
    query: "secarropas",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/termotanque-electrico-rheem-electrico-50l/p/MLA13100000",
    title: "Termotanque Eléctrico Rheem 50L",
    price: 289000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "RHEEM",
    query: "termotanque",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/horno-electrico-ultracomb-uc-70rcl-70l/p/MLA12600000",
    title: "Horno Eléctrico Ultracomb UC-70RCL 70L",
    price: 229000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ULTRACOMB",
    query: "horno electrico",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/licuadora-oster-bpst02-600w-vidrio/p/MLA10100000",
    title: "Licuadora Oster BPST02 600W Vaso de Vidrio",
    price: 99999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "OSTER",
    query: "licuadora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/batidora-de-mano-philips-hr3705-300w/p/MLA10200000",
    title: "Batidora de Mano Philips HR3705 300W",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "batidora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/pava-electrica-atma-pe3825-1-7l/p/MLA34010005",
    title: "Pava Eléctrica Atma PE-3825 1.7L",
    price: 39999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ATMA",
    query: "pava electrica",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/tostadora-liliana-t2a-doble-pinza/p/MLA34010006",
    title: "Tostadora Liliana T2A Doble Pinza",
    price: 24999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LILIANA",
    query: "tostadora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/freezer-vertical-inelro-iff200-200l/p/MLA34010007",
    title: "Freezer Vertical Inelro IFF200 200L",
    price: 599000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "INELRO",
    query: "freezer",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/secador-de-pelo-philips-bhd318-2200w/p/MLA34010008",
    title: "Secador de Pelo Philips BHD318 2200W",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "secador de pelo",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/plancha-de-pelo-philips-bhs393-230c/p/MLA34010009",
    title: "Plancha de Pelo Philips BHS393 230°C",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "plancha de pelo",
  },
  // Hogar / muebles
  {
    permalink: "https://www.mercadolibre.com.ar/colchon-piero-divino-resortes-2-plazas-190x140/p/MLA13600000",
    title: "Colchón Piero Divino Resortes 2 Plazas 190x140",
    price: 469000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PIERO",
    query: "colchon",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/silla-gamer-redragon-coeus-c201-rgb/p/MLA17400000",
    title: "Silla Gamer Redragon Coeus C201 RGB",
    price: 269000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "REDRAGON",
    query: "silla gamer",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/sillon-reclinable-de-living-3-cuerpos-eco-cuero/p/MLA13800000",
    title: "Sillón Reclinable de Living 3 Cuerpos Eco Cuero",
    price: 899000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "sillon",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/escritorio-pc-melamina-120cm-con-cajon/p/MLA10800000",
    title: "Escritorio PC Melamina 120cm con Cajón",
    price: 159000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "escritorio",
  },
  // Deportes / outdoor
  {
    permalink: "https://www.mercadolibre.com.ar/bicicleta-mtb-rodado-29-aluminio-21-velocidades/p/MLA16900000",
    title: "Bicicleta MTB Rodado 29 Aluminio 21 Velocidades",
    price: 459000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "bicicleta",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/zapatillas-nike-revolution-7-running/p/MLA20100000",
    title: "Zapatillas Nike Revolution 7 Running",
    price: 119999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "NIKE OFICIAL",
    query: "zapatillas",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/mochila-jansport-superbreak-original-25l/p/MLA11200000",
    title: "Mochila JanSport SuperBreak Original 25L",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "JANSPORT",
    query: "mochila",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/pelota-futbol-adidas-tiro-league-n5/p/MLA11500000",
    title: "Pelota de Fútbol adidas Tiro League N°5",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ADIDAS",
    query: "pelota",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/carpa-iglu-doite-trekko-4-personas/p/MLA12700000",
    title: "Carpa Iglú Doite Trekko 4 Personas",
    price: 269000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DOITE",
    query: "carpa",
  },
  // Moda / belleza
  {
    permalink: "https://www.mercadolibre.com.ar/perfume-carolina-herrera-good-girl-edp-80ml/p/MLA9800000",
    title: "Perfume Carolina Herrera Good Girl EDP 80ml",
    price: 189999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PERFUMERIA OFICIAL",
    query: "perfume",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/reloj-casio-g-shock-ga-2100-1a1/p/MLA14200000",
    title: "Reloj Casio G-Shock GA-2100-1A1",
    price: 199999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "CASIO",
    query: "reloj",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/campera-puffer-inflable-impermeable-unisex/p/MLA14400000",
    title: "Campera Puffer Inflable Impermeable Unisex",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "campera",
  },
  // Infantil
  {
    permalink: "https://www.mercadolibre.com.ar/auto-a-bateria-mercedes-benz-12v-control-remoto/p/MLA13500000",
    title: "Auto a Batería Mercedes-Benz 12V con Control Remoto",
    price: 289000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "auto a bateria",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/juguete-rasti-bloques-creativos-200-piezas/p/MLA10600000",
    title: "Rasti Bloques Creativos 200 Piezas",
    price: 39999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "RASTI",
    query: "juguetes",
  },
  // Herramientas
  {
    permalink: "https://www.mercadolibre.com.ar/taladro-percutor-bosch-gsb-13-re-650w/p/MLA10300000",
    title: "Taladro Percutor Bosch GSB 13 RE 650W",
    price: 129000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BOSCH",
    query: "taladro",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/amoladora-angular-dewalt-dwe4120-720w/p/MLA10400000",
    title: "Amoladora Angular DeWalt DWE4120 720W",
    price: 159000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DEWALT",
    query: "amoladora",
  },
  // Tech adicional
  {
    permalink: "https://www.mercadolibre.com.ar/router-wifi-tp-link-archer-ax23-ax1800-dual-band/p/MLA34020001",
    title: "Router WiFi TP-Link Archer AX23 AX1800 Dual Band",
    price: 69999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TP-LINK",
    query: "router wifi",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/joystick-inalambrico-sony-dualshock-4-ps4/p/MLA34020002",
    title: "Joystick Inalámbrico Sony DualShock 4 PS4",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SONY ARGENTINA",
    query: "joystick",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-gamer-lenovo-loq-intel-core-i5-16gb-512gb-rtx3050/p/MLA34020003",
    title: "Notebook Gamer Lenovo LOQ Intel Core i5 16GB 512GB RTX 3050",
    price: 1899000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LENOVO",
    query: "notebook gamer",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/camara-de-seguridad-tp-link-tapo-c200-wifi-360/p/MLA34020004",
    title: "Cámara de Seguridad TP-Link Tapo C200 WiFi 360°",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TP-LINK",
    query: "camara de seguridad",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/robot-aspiradora-xiaomi-mi-robot-vacuum-x10-plus/p/MLA34020005",
    title: "Robot Aspiradora Xiaomi Mi Robot Vacuum X10 Plus",
    price: 589000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "XIAOMI",
    query: "robot aspiradora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/disco-rigido-externo-wd-elements-portable-1tb-usb/p/MLA34020006",
    title: "Disco Rígido Externo WD Elements Portable 1TB USB 3.0",
    price: 59999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "WESTERN DIGITAL",
    query: "disco rigido externo",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/mouse-gamer-redragon-m602-griffin-7200dpi-rgb/p/MLA34020007",
    title: "Mouse Gamer Redragon M602 Griffin 7200DPI RGB",
    price: 24999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "REDRAGON",
    query: "mouse gamer",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/teclado-mecanico-redragon-k552-kumara-rgb-red-switch/p/MLA34020008",
    title: "Teclado Mecánico Redragon K552 Kumara RGB Red Switch",
    price: 44999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "REDRAGON",
    query: "teclado mecanico",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/webcam-logitech-c920-hd-pro-1080p-usb/p/MLA34020009",
    title: "Webcam Logitech C920 HD Pro 1080p USB",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LOGITECH",
    query: "webcam",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/disco-solido-kingston-nv2-1tb-m2-nvme/p/MLA34020010",
    title: "Disco Sólido Kingston NV2 1TB M.2 NVMe",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "KINGSTON",
    query: "disco solido",
  },
  // Línea blanca adicional
  {
    permalink: "https://www.mercadolibre.com.ar/lavavajillas-whirlpool-wdf530plym-12-cubiertos/p/MLA34020011",
    title: "Lavavajillas Whirlpool WDF530PLYM 12 Cubiertos",
    price: 1199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "WHIRLPOOL",
    query: "lavavajillas",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/purificador-de-aire-philips-ac1715-para-60m2/p/MLA34020012",
    title: "Purificador de Aire Philips AC1715 para 60m²",
    price: 349000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "purificador de aire",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/sandwichera-oster-ckstst2150-750w-antiadherente/p/MLA34020013",
    title: "Sandwichera Oster CKSTST2150 750W Antiadherente",
    price: 29999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "OSTER",
    query: "sandwichera",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/procesadora-oster-fpstfp2250-500w-1-5l/p/MLA34020014",
    title: "Procesadora Oster FPSTFP2250 500W 1.5L",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "OSTER",
    query: "procesadora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/termo-stanley-classic-acero-inoxidable-470ml/p/MLA34020015",
    title: "Termo Stanley Classic Acero Inoxidable 470ml",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "STANLEY",
    query: "termo",
  },
  // Hogar adicional
  {
    permalink: "https://www.mercadolibre.com.ar/sommier-piero-doble-felicidad-2-plazas-190x140/p/MLA34020016",
    title: "Sommier Piero Doble Felicidad 2 Plazas 190x140cm",
    price: 699000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PIERO",
    query: "sommier",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/silla-de-oficina-mesh-altura-regulable-con-apoyabrazos/p/MLA34020017",
    title: "Silla de Oficina Mesh Altura Regulable con Apoyabrazos",
    price: 189000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "silla de oficina",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/lampara-led-philips-10w-e27-luz-blanca-pack-3/p/MLA34020018",
    title: "Lámpara LED Philips 10W E27 Luz Blanca Pack x3",
    price: 12999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "lampara led",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/alarma-para-casa-paradox-mg5050-inalambrica-zona/p/MLA34020019",
    title: "Alarma para Casa Paradox MG5050 Inalámbrica",
    price: 249000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PARADOX",
    query: "alarma casa",
  },
  // Deportes / fitness
  {
    permalink: "https://www.mercadolibre.com.ar/monopatin-electrico-xiaomi-mi-electric-scooter-3/p/MLA34020020",
    title: "Monopatín Eléctrico Xiaomi Mi Electric Scooter 3",
    price: 799000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "XIAOMI",
    query: "monopatin electrico",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/bicicleta-fija-olmo-fitness-50-magnetica-8-vel/p/MLA34020021",
    title: "Bicicleta Fija Olmo Fitness 50 Magnética 8 Vel",
    price: 359000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "OLMO",
    query: "bicicleta fija",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/cinta-de-correr-weslo-cadence-g59i-motorizada/p/MLA34020022",
    title: "Cinta de Correr Weslo Cadence G 5.9i Motorizada",
    price: 599000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "WESLO",
    query: "cinta de correr",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/mancuernas-hexagonales-hierro-fundido-10kg-par/p/MLA34020023",
    title: "Mancuernas Hexagonales Hierro Fundido 10kg Par",
    price: 29999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "pesas",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/colchoneta-yoga-everlast-6mm-antideslizante/p/MLA34020024",
    title: "Colchoneta Yoga Everlast 6mm Antideslizante",
    price: 19999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "EVERLAST",
    query: "colchoneta yoga",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/eliptica-bh-fitness-g2377-magnetic-6kg-volante/p/MLA34020025",
    title: "Elíptica BH Fitness G2377 Magnética 6kg Volante",
    price: 589000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BH FITNESS",
    query: "eliptica",
  },
  // Mascotas
  {
    permalink: "https://www.mercadolibre.com.ar/alimento-perro-royal-canin-adult-15kg/p/MLA34020026",
    title: "Alimento Perro Royal Canin Adult 15kg",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ROYAL CANIN",
    query: "alimento perro",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/alimento-gato-royal-canin-cat-adult-7-5kg/p/MLA34020027",
    title: "Alimento Gato Royal Canin Cat Adult 7.5kg",
    price: 54999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ROYAL CANIN",
    query: "alimento gato",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/comedero-automatico-pet-feeder-wifi-app-5l/p/MLA34020028",
    title: "Comedero Automático Pet Feeder WiFi App 5L",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "comedero automatico",
  },
  // Auto / moto
  {
    permalink: "https://www.mercadolibre.com.ar/bateria-auto-rema-12v-60ah-libre-mantenimiento/p/MLA34020029",
    title: "Batería Auto Rema 12V 60Ah Libre de Mantenimiento",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "REMA",
    query: "bateria auto",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/gps-garmin-drivesmart-55-pantalla-55-mapas-sudamerica/p/MLA34020030",
    title: "GPS Garmin DriveSmart 55 Pantalla 5.5\" Mapas Sudamérica",
    price: 179000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "GARMIN",
    query: "gps auto",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/casco-moto-integral-ls2-ff320-stream-evo/p/MLA34020031",
    title: "Casco Moto Integral LS2 FF320 Stream EVO",
    price: 129000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LS2",
    query: "casco moto",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/silla-auto-bebe-chicco-oasys-2-3-fixplus-15-36kg/p/MLA34020032",
    title: "Silla Auto Bebé Chicco Oasys 2-3 FixPlus 15-36kg",
    price: 349000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "CHICCO",
    query: "silla auto bebe",
  },
  // Herramientas adicional
  {
    permalink: "https://www.mercadolibre.com.ar/sierra-circular-dewalt-dwe575sb-184mm-1600w/p/MLA34020033",
    title: "Sierra Circular DeWalt DWE575SB 184mm 1600W",
    price: 249000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DEWALT",
    query: "sierra circular",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/compresor-de-aire-black-decker-bd195-50-50l-1hp/p/MLA34020034",
    title: "Compresor de Aire Black & Decker BD195/50 50L 1HP",
    price: 179000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BLACK AND DECKER",
    query: "compresor de aire",
  },
  // Bebés / puericultura adicional
  {
    permalink: "https://www.mercadolibre.com.ar/cuna-infanti-nova-cuna-convertible-con-colchon/p/MLA34020035",
    title: "Cuna Infanti Nova Convertible con Colchón",
    price: 299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "INFANTI",
    query: "cuna",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/cochecito-infanti-slim-paseo-compacto/p/MLA34020036",
    title: "Cochecito Infanti Slim Paseo Compacto",
    price: 199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "INFANTI",
    query: "cochecito",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/silla-de-comer-bebe-chicco-polly-2start-5-posiciones/p/MLA34020037",
    title: "Silla de Comer Bebé Chicco Polly 2start 5 Posiciones",
    price: 249000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "CHICCO",
    query: "silla de comer bebe",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/andador-bebe-infanti-lively-con-musica-luces/p/MLA34020038",
    title: "Andador Bebé Infanti Lively con Música y Luces",
    price: 69999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "INFANTI",
    query: "andador bebe",
  },
  // Climatización adicional
  {
    permalink: "https://www.mercadolibre.com.ar/calefactor-calobar-1500w-bajo-consumo-termostato/p/MLA34020039",
    title: "Calefactor Calobar 1500W Bajo Consumo con Termostato",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "CALOBAR",
    query: "calefactor",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/estufa-electrica-liliana-ce2100-2000w-ceramica/p/MLA34020040",
    title: "Estufa Eléctrica Liliana CE2100 2000W Cerámica",
    price: 59999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LILIANA",
    query: "estufa electrica",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/caloventor-philips-hb5341-2300w-oscilante/p/MLA34020041",
    title: "Caloventor Philips HB5341 2300W Oscilante",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "caloventor",
  },
  // Electrohogar adicional
  {
    permalink: "https://www.mercadolibre.com.ar/purificador-agua-drago-filtro-triple-etapa-bajo-mesada/p/MLA34020042",
    title: "Purificador Agua Drago Filtro Triple Etapa Bajo Mesada",
    price: 149000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DRAGO",
    query: "purificador agua",
  },
  // Hogar inteligente / smart home
  {
    permalink: "https://www.mercadolibre.com.ar/parlante-inteligente-amazon-echo-dot-5ta-gen-alexa/p/MLA34020043",
    title: "Parlante Inteligente Amazon Echo Dot 5ta Gen con Alexa",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "AMAZON",
    query: "parlante inteligente",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/lampara-inteligente-philips-hue-white-e27-9w-wifi/p/MLA34020044",
    title: "Lámpara Inteligente Philips Hue White E27 9W WiFi",
    price: 24999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "lampara inteligente",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/enchufe-inteligente-tp-link-tapo-p100-wifi-control-remoto/p/MLA34020045",
    title: "Enchufe Inteligente TP-Link Tapo P100 WiFi Control Remoto",
    price: 12999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TP-LINK",
    query: "enchufe inteligente",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/timbre-con-camara-ring-video-doorbell-3-wifi/p/MLA34020046",
    title: "Timbre con Cámara Ring Video Doorbell 3 WiFi",
    price: 119000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "RING",
    query: "timbre con camara",
  },
  // Gaming / accesorios adicional
  {
    permalink: "https://www.mercadolibre.com.ar/silla-gamer-reclinable-redragon-medha-s107w-con-reposapiés/p/MLA34020047",
    title: "Silla Gamer Reclinable Redragon Medha S107-W con Reposapiés",
    price: 329000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "REDRAGON",
    query: "silla gamer reclinable",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/auriculares-gamer-hyperx-cloud-stinger-2-pc/p/MLA34020048",
    title: "Auriculares Gamer HyperX Cloud Stinger 2 PC",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "HYPERX",
    query: "auriculares gamer",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/monitor-gamer-msi-g27c4x-27-180hz-fhd-va/p/MLA34020049",
    title: "Monitor Gamer MSI G27C4X 27\" 180Hz FHD VA",
    price: 549000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MSI",
    query: "monitor gamer",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/control-xbox-inalambrico-microsoft-carbon-black/p/MLA34020050",
    title: "Control Xbox Inalámbrico Microsoft Carbon Black",
    price: 59999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MICROSOFT",
    query: "control xbox",
  },
  // Oficina / estudio adicional
  {
    permalink: "https://www.mercadolibre.com.ar/silla-ergonomica-mesh-lumbar-ajustable-brazos/p/MLA34020051",
    title: "Silla Ergonómica Mesh Lumbar Ajustable con Brazos",
    price: 249000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "silla ergonomica",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/soporte-notebook-fellowes-ispan-regulable-aluminio/p/MLA34020052",
    title: "Soporte Notebook Fellowes iSpan Regulable Aluminio",
    price: 29999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "FELLOWES",
    query: "soporte notebook",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/hub-usb-anker-7-puertos-usb-30-con-carga/p/MLA34020053",
    title: "Hub USB Anker 7 Puertos USB 3.0 con Carga",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ANKER",
    query: "hub usb",
  },
  // Cuidado personal
  {
    permalink: "https://www.mercadolibre.com.ar/afeitadora-electrica-philips-series-3000-s3233-wet-dry/p/MLA34020054",
    title: "Afeitadora Eléctrica Philips Series 3000 S3233 Wet&Dry",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "afeitadora electrica",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/depiladora-braun-silk-epil-5-5579-seco-humedo/p/MLA34020055",
    title: "Depiladora Braun Silk-épil 5 5579 Seco/Húmedo",
    price: 109999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BRAUN",
    query: "depiladora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/cepillo-dental-electrico-oral-b-vitality-100-2d/p/MLA34020056",
    title: "Cepillo Dental Eléctrico Oral-B Vitality 100 2D",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ORAL-B",
    query: "cepillo dental electrico",
  },
  // Nutrición / salud
  {
    permalink: "https://www.mercadolibre.com.ar/proteina-whey-bsn-syntha-6-edge-1-86kg-chocolate/p/MLA34020057",
    title: "Proteína Whey BSN Syntha-6 Edge 1.86kg Chocolate",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BSN",
    query: "proteina whey",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/creatina-monohidrato-quamtrax-300g-unflavoured/p/MLA34020058",
    title: "Creatina Monohidrato Quamtrax 300g Unflavoured",
    price: 24999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "QUAMTRAX",
    query: "suplemento deportivo",
  },
  // Audio / video adicional
  {
    permalink: "https://www.mercadolibre.com.ar/barra-de-sonido-jbl-bar-21-deep-bass-300w/p/MLA34020059",
    title: "Barra de Sonido JBL Bar 2.1 Deep Bass 300W",
    price: 349000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "JBL OFICIAL",
    query: "barra de sonido",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/proyector-epson-home-cinema-760hd-3lcd-3400-lumens/p/MLA34020060",
    title: "Proyector Epson Home Cinema 760HD 3LCD 3400 Lúmenes",
    price: 799000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "EPSON",
    query: "proyector",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/tocadiscos-bluetooth-parlante-integrado-aux-usb/p/MLA34020061",
    title: "Tocadiscos Vinilo con Parlante Integrado Bluetooth USB",
    price: 149000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "vinilo parlante",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/camara-gopro-hero11-black-5-3k-estabilizacion/p/MLA34020062",
    title: "Cámara GoPro HERO11 Black 5.3K Estabilización",
    price: 699000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "GOPRO",
    query: "camara gopro",
  },
  // Hot Sale 2026 — Apple / premium brand flagships
  {
    permalink: "https://www.mercadolibre.com.ar/apple-iphone-15-128-gb-negro/p/MLA26780000",
    title: "Apple iPhone 15 128 GB Negro",
    price: 2499000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE ARGENTINA",
    query: "iphone",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/apple-ipad-10a-generacion-64gb-wifi/p/MLA27180000",
    title: "Apple iPad 10ª Generación 64GB Wi-Fi",
    price: 1199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE ARGENTINA",
    query: "ipad",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/apple-watch-series-9-gps-41mm/p/MLA27500000",
    title: "Apple Watch Series 9 GPS 41mm",
    price: 899000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE ARGENTINA",
    query: "apple watch",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/apple-macbook-air-m2-8gb-256gb/p/MLA27800000",
    title: "Apple MacBook Air M2 8GB 256GB",
    price: 3499000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE ARGENTINA",
    query: "macbook",
  },
  // Hot Sale 2026 — movilidad eléctrica
  {
    permalink: "https://www.mercadolibre.com.ar/moto-electrica-chetak-urbana-3000w/p/MLA34100001",
    title: "Moto Eléctrica Chetak Urbana 3000W",
    price: 4500000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "moto electrica",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/bicicleta-electrica-oxford-e-bike-350w/p/MLA34100002",
    title: "Bicicleta Eléctrica Oxford E-Bike 350W",
    price: 699000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "bicicleta electrica",
  },
  // Hot Sale 2026 — ropa / moda deportiva
  {
    permalink: "https://www.mercadolibre.com.ar/zapatillas-nike-air-max-270-hombre/p/MLA34100003",
    title: "Zapatillas Nike Air Max 270 Hombre Running",
    price: 129999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "NIKE ARGENTINA",
    query: "zapatillas running",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/zapatillas-nike-downshifter-12-running/p/MLA34100004",
    title: "Zapatillas Nike Downshifter 12 Running",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "NIKE ARGENTINA",
    query: "zapatillas nike",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/zapatillas-adidas-ultraboost-22-running/p/MLA34100005",
    title: "Zapatillas Adidas Ultraboost 22 Running",
    price: 149999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ADIDAS ARGENTINA",
    query: "zapatillas adidas",
  },
  // Hot Sale 2026 — conectividad / trabajo remoto
  {
    permalink: "https://www.mercadolibre.com.ar/ups-apc-back-ups-600va-bk600-ei/p/MLA34100006",
    title: "UPS APC Back-UPS 600VA BK600-EI",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APC",
    query: "ups para pc",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/adaptador-usb-c-7-en-1-hub-hdmi-4k/p/MLA34100007",
    title: "Adaptador USB-C 7 en 1 Hub HDMI 4K",
    price: 29999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "adaptador usb c",
  },
  // Hot Sale 2026 — hogar inteligente adicional
  {
    permalink: "https://www.mercadolibre.com.ar/cerradura-inteligente-yale-linus-bluetooth/p/MLA34100008",
    title: "Cerradura Inteligente Yale Linus Bluetooth",
    price: 199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "YALE",
    query: "cerradura inteligente",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/camara-ip-wifi-360-grados-full-hd-1080p/p/MLA34100009",
    title: "Cámara IP WiFi 360° Full HD 1080p",
    price: 39999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "camara ip wifi",
  },
  // Hot Sale 2026 — audio premium
  {
    permalink: "https://www.mercadolibre.com.ar/auriculares-noise-cancelling-sony-wh1000xm5/p/MLA34100010",
    title: "Auriculares Sony WH-1000XM5 Noise Cancelling",
    price: 349000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SONY ARGENTINA",
    query: "auriculares noise cancelling",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/auriculares-sony-wf-1000xm4-true-wireless/p/MLA34100011",
    title: "Auriculares Sony WF-1000XM4 True Wireless",
    price: 219000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SONY ARGENTINA",
    query: "auriculares sony",
  },
  // CyberMonday Nov 2026 — gaming
  {
    permalink: "https://www.mercadolibre.com.ar/consola-playstation-5-slim-1tb/p/MLA34200001",
    title: "Consola PlayStation 5 Slim 1TB",
    price: 1199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SONY ARGENTINA",
    query: "ps5 consola",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/consola-xbox-series-x-1tb/p/MLA34200002",
    title: "Consola Xbox Series X 1TB",
    price: 1099000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MICROSOFT",
    query: "xbox series x",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/nintendo-switch-oled-blanco-64gb/p/MLA34200003",
    title: "Nintendo Switch OLED Blanco 64GB",
    price: 699000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "NINTENDO",
    query: "nintendo switch oled",
  },
  // CyberMonday Nov 2026 — audio
  {
    permalink: "https://www.mercadolibre.com.ar/soundbar-samsung-hw-b550-2-1-canales/p/MLA34200004",
    title: "Soundbar Samsung HW-B550 2.1 Canales 410W",
    price: 249000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "soundbar samsung",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/apple-airpods-pro-2da-generacion-usb-c/p/MLA34200005",
    title: "Apple AirPods Pro 2da Generación USB-C",
    price: 419000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE",
    query: "airpods",
  },
  // CyberMonday Nov 2026 — computación
  {
    permalink: "https://www.mercadolibre.com.ar/monitor-lg-ultragear-27-4k-144hz/p/MLA34200006",
    title: "Monitor LG UltraGear 27\" 4K 144Hz",
    price: 549000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LG ARGENTINA",
    query: "monitor 4k",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-acer-aspire-5-core-i5-8gb-512ssd/p/MLA34200007",
    title: "Notebook Acer Aspire 5 Core i5 8GB 512GB SSD",
    price: 849000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ACER",
    query: "notebook acer",
  },
  // CyberMonday Nov 2026 — smart home
  {
    permalink: "https://www.mercadolibre.com.ar/amazon-echo-dot-5ta-generacion/p/MLA34200008",
    title: "Amazon Echo Dot 5ta Generación con Alexa",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "smart speaker alexa",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/google-chromecast-4k-con-google-tv/p/MLA34200009",
    title: "Google Chromecast 4K con Google TV",
    price: 59999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "chromecast",
  },
  // CyberMonday Nov 2026 — movilidad
  {
    permalink: "https://www.mercadolibre.com.ar/monopatin-xiaomi-electric-scooter-4-lite/p/MLA34200010",
    title: "Monopatín Eléctrico Xiaomi Electric Scooter 4 Lite",
    price: 549000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "XIAOMI",
    query: "monopatin xiaomi",
  },
  // Hot Sale 2026 — marcas phones
  {
    permalink: "https://www.mercadolibre.com.ar/celular-samsung-galaxy-s24-256gb-12gb-ram/p/MLA35000001",
    title: "Celular Samsung Galaxy S24 256GB 12GB RAM",
    price: 1299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "samsung galaxy",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/celular-xiaomi-13t-256gb-12gb-ram/p/MLA35000002",
    title: "Celular Xiaomi 13T 256GB 12GB RAM",
    price: 899000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "XIAOMI",
    query: "xiaomi celular",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/celular-motorola-moto-g85-256gb-12gb-ram/p/MLA35000003",
    title: "Celular Motorola Moto G85 256GB 12GB RAM",
    price: 549000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MOTOROLA",
    query: "motorola celular",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/celular-realme-c67-128gb-6gb-ram/p/MLA35000004",
    title: "Celular Realme C67 128GB 6GB RAM",
    price: 279000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "REALME",
    query: "realme celular",
  },
  // Hot Sale 2026 — TV por marca
  {
    permalink: "https://www.mercadolibre.com.ar/smart-tv-samsung-55-crystal-uhd-4k/p/MLA35000005",
    title: "Smart TV Samsung 55\" Crystal UHD 4K",
    price: 849000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "samsung smart tv",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/smart-tv-lg-55-nanocell-4k/p/MLA35000006",
    title: "Smart TV LG 55\" NanoCell 4K",
    price: 899000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LG ARGENTINA",
    query: "lg smart tv",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/smart-tv-tcl-55-qled-4k-google-tv/p/MLA35000007",
    title: "Smart TV TCL 55\" QLED 4K Google TV",
    price: 649000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TCL",
    query: "tcl televisor",
  },
  // Hot Sale 2026 — notebooks por marca
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-lenovo-ideapad-3-core-i5-8gb-512ssd/p/MLA35000008",
    title: "Notebook Lenovo IdeaPad 3 Core i5 8GB 512GB SSD",
    price: 999000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LENOVO",
    query: "lenovo notebook",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-hp-250-g9-core-i5-8gb-512ssd/p/MLA35000009",
    title: "Notebook HP 250 G9 Core i5 8GB 512GB SSD",
    price: 949000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "HP",
    query: "hp notebook",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-dell-inspiron-15-core-i5-8gb-512ssd/p/MLA35000010",
    title: "Notebook Dell Inspiron 15 Core i5 8GB 512GB SSD",
    price: 1049000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DELL",
    query: "dell notebook",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-asus-vivobook-15-core-i5-16gb-512ssd/p/MLA35000011",
    title: "Notebook ASUS VivoBook 15 Core i5 16GB 512GB SSD",
    price: 1099000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ASUS",
    query: "asus notebook",
  },
  // Hot Sale 2026 — electrodomésticos premium
  {
    permalink: "https://www.mercadolibre.com.ar/aspiradora-dyson-v15-detect/p/MLA35000012",
    title: "Aspiradora Inalámbrica Dyson V15 Detect",
    price: 849000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DYSON",
    query: "dyson aspiradora",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/roomba-irobot-j7-plus-robot-aspiradora/p/MLA35000013",
    title: "Robot Aspiradora iRobot Roomba j7+ con vaciado automático",
    price: 749000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "IROBOT",
    query: "roomba",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/freidora-de-aire-philips-airfryer-xxl/p/MLA35000014",
    title: "Freidora de Aire Philips Airfryer XXL 7.3L",
    price: 349000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "philips airfryer",
  },
  // Hot Sale 2026 — gaming hardware
  {
    permalink: "https://www.mercadolibre.com.ar/placa-de-video-nvidia-geforce-rtx-4060/p/MLA35000015",
    title: "Placa de Video NVIDIA GeForce RTX 4060 8GB",
    price: 899000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "nvidia rtx",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/procesador-intel-core-i5-13400-lga1700/p/MLA35000016",
    title: "Procesador Intel Core i5-13400 LGA1700 2.5GHz",
    price: 349000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "procesador intel",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/procesador-amd-ryzen-5-7600x-am5/p/MLA35000017",
    title: "Procesador AMD Ryzen 5 7600X AM5 4.7GHz",
    price: 379000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "procesador amd ryzen",
  },
  // Hot Sale 2026 — audio/foto
  {
    permalink: "https://www.mercadolibre.com.ar/camara-mirrorless-sony-zve10-24mp/p/MLA35000018",
    title: "Cámara Mirrorless Sony ZV-E10 24MP APS-C",
    price: 749000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SONY",
    query: "camara sony",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/camara-reflex-canon-eos-rebel-sl3-24mp/p/MLA35000019",
    title: "Cámara Réflex Canon EOS Rebel SL3 24MP",
    price: 849000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "CANON",
    query: "camara canon",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/lente-canon-ef-50mm-f18-stm/p/MLA35000020",
    title: "Lente Canon EF 50mm f/1.8 STM",
    price: 189000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "CANON",
    query: "lente camara",
  },
  // Hot Sale 2026 — indumentaria deportiva
  {
    permalink: "https://www.mercadolibre.com.ar/zapatillas-puma-rs-x-tonal/p/MLA35000021",
    title: "Zapatillas Puma RS-X Tonal",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PUMA",
    query: "zapatillas puma",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/zapatillas-under-armour-charged-pursuit-3/p/MLA35000022",
    title: "Zapatillas Under Armour Charged Pursuit 3",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "UNDER ARMOUR",
    query: "zapatillas under armour",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/conjunto-deportivo-adidas-tiro-23/p/MLA35000023",
    title: "Conjunto Deportivo Adidas Tiro 23",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ADIDAS",
    query: "ropa deportiva",
  },
  // Hot Sale 2026 — modelos específicos phones
  {
    permalink: "https://www.mercadolibre.com.ar/apple-iphone-16-128gb/p/MLA35000024",
    title: "Apple iPhone 16 128GB",
    price: 2199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE",
    query: "iphone 16",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/apple-iphone-15-128gb/p/MLA35000025",
    title: "Apple iPhone 15 128GB",
    price: 1799000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE",
    query: "iphone 15",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/samsung-galaxy-s24-256gb-negro/p/MLA35000026",
    title: "Samsung Galaxy S24 256GB Phantom Black",
    price: 1299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "samsung galaxy s24",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/samsung-galaxy-a55-5g-256gb/p/MLA35000027",
    title: "Samsung Galaxy A55 5G 256GB",
    price: 699000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "samsung galaxy a55",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/motorola-edge-50-fusion-256gb/p/MLA35000028",
    title: "Motorola Edge 50 Fusion 256GB",
    price: 749000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MOTOROLA",
    query: "motorola edge 50",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/xiaomi-redmi-note-13-pro-256gb/p/MLA35000029",
    title: "Xiaomi Redmi Note 13 Pro 256GB",
    price: 449000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "XIAOMI",
    query: "xiaomi redmi note",
  },
  // Hot Sale 2026 — TVs por pulgadas
  {
    permalink: "https://www.mercadolibre.com.ar/smart-tv-samsung-55-qled-4k-q60c/p/MLA35000030",
    title: "Smart TV Samsung 55\" QLED 4K Q60C",
    price: 799000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "smart tv 55 pulgadas",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/smart-tv-tcl-65-qled-4k-google-tv/p/MLA35000031",
    title: "Smart TV TCL 65\" QLED 4K Google TV",
    price: 999000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TCL",
    query: "smart tv 65 pulgadas",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/smart-tv-hisense-43-uhd-4k-vidaa/p/MLA35000032",
    title: "Smart TV Hisense 43\" UHD 4K VIDAA",
    price: 499000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "HISENSE",
    query: "smart tv 43 pulgadas",
  },
  // Hot Sale 2026 — notebooks gamer por marca
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-gamer-lenovo-legion-5-rtx4060/p/MLA35000033",
    title: "Notebook Gamer Lenovo Legion 5 Gen 9 RTX 4060",
    price: 2499000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LENOVO",
    query: "lenovo legion",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-gamer-asus-rog-strix-g16-rtx4070/p/MLA35000034",
    title: "Notebook Gamer ASUS ROG Strix G16 RTX 4070",
    price: 3299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ASUS",
    query: "asus rog",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/notebook-gamer-msi-katana-15-rtx4060/p/MLA35000035",
    title: "Notebook Gamer MSI Katana 15 RTX 4060",
    price: 2199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MSI",
    query: "msi notebook",
  },
  // Hot Sale 2026 — accesorios tech
  {
    permalink: "https://www.mercadolibre.com.ar/cargador-inalambrico-samsung-15w-fast-charge/p/MLA35000036",
    title: "Cargador Inalámbrico Samsung 15W Fast Charge",
    price: 29999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "cargador inalambrico",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/cable-usb-c-anker-100w-1-8m/p/MLA35000037",
    title: "Cable USB-C Anker 100W 1.8m Nylon",
    price: 14999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "ANKER",
    query: "cable usb c",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/funda-silicona-apple-iphone-15-magsafe/p/MLA35000038",
    title: "Funda Silicona Apple iPhone 15 con MagSafe",
    price: 19999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE",
    query: "funda celular",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/vidrio-templado-gorilla-glass-iphone-15/p/MLA35000039",
    title: "Vidrio Templado Gorilla Glass iPhone 15",
    price: 9999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "vidrio templado celular",
  },
  // Hot Sale 2026 — cafeteras premium
  {
    permalink: "https://www.mercadolibre.com.ar/cafetera-nespresso-vertuo-pop/p/MLA35000040",
    title: "Cafetera Nespresso Vertuo Pop",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "NESPRESSO",
    query: "cafetera nespresso",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/cafetera-dolce-gusto-neo/p/MLA35000041",
    title: "Cafetera Dolce Gusto Neo",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DOLCE GUSTO",
    query: "cafetera dolce gusto",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/licuadora-oster-blstmg-1200w/p/MLA35000042",
    title: "Licuadora Oster BLSTMG 1200W Vaso Tritan",
    price: 69999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "OSTER",
    query: "licuadora oster",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/olla-arrocera-philips-1-8l/p/MLA35000043",
    title: "Olla Arrocera Philips 1.8L 700W",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "olla arrocera",
  },
  // Hot Sale 2026 — climatización residencial
  {
    permalink: "https://www.mercadolibre.com.ar/aire-acondicionado-split-inverter-3000w-frio-calor/p/MLA35000044",
    title: "Aire Acondicionado Split Inverter 3000W Frío/Calor",
    price: 799000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "aire acondicionado split",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/ventilador-de-torre-4-velocidades-75cm/p/MLA35000045",
    title: "Ventilador de Torre 75cm 4 Velocidades",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "ventilador de torre",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/purificador-de-aire-hepa-h13-winix-am90/p/MLA35000046",
    title: "Purificador de Aire HEPA H13 Winix AM90",
    price: 199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "WINIX",
    query: "purificador de aire hepa",
  },
  // Hot Sale 2026 — hogar/decoración
  {
    permalink: "https://www.mercadolibre.com.ar/lampara-de-pie-trípode-madera-e27/p/MLA35000047",
    title: "Lámpara de Pie Trípode Madera E27",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "lampara de pie",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/ventilador-de-techo-con-luz-led-4-aspas/p/MLA35000048",
    title: "Ventilador de Techo con Luz LED 4 Aspas 48\"",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "ventilador de techo",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/cortina-roller-blackout-140x200cm/p/MLA35000049",
    title: "Cortina Roller Blackout 140x200cm",
    price: 24999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "cortina roller",
  },
  // CyberMonday Nov 2026 — phones
  {
    permalink: "https://www.mercadolibre.com.ar/apple-iphone-17-128gb/p/MLA35000050",
    title: "Apple iPhone 17 128GB",
    price: 2499000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE",
    query: "iphone 17",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/samsung-galaxy-s25-256gb/p/MLA35000051",
    title: "Samsung Galaxy S25 256GB",
    price: 1499000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "samsung galaxy s25",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/samsung-galaxy-a56-5g-128gb/p/MLA35000052",
    title: "Samsung Galaxy A56 5G 128GB",
    price: 649000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "samsung galaxy a56",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/motorola-edge-60-pro-256gb/p/MLA35000053",
    title: "Motorola Edge 60 Pro 256GB",
    price: 899000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MOTOROLA",
    query: "motorola edge 60",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/xiaomi-15-512gb-16gb-ram/p/MLA35000054",
    title: "Xiaomi 15 512GB 16GB RAM",
    price: 1299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "XIAOMI",
    query: "xiaomi 15",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/tablet-samsung-galaxy-tab-a9-plus-128gb/p/MLA35000055",
    title: "Tablet Samsung Galaxy Tab A9+ 128GB",
    price: 449000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "tablet samsung",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/apple-ipad-pro-m4-11-pulgadas-256gb/p/MLA35000056",
    title: "Apple iPad Pro M4 11 Pulgadas 256GB",
    price: 2199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "APPLE",
    query: "ipad pro",
  },
  // CyberMonday Nov 2026 — gaming
  {
    permalink: "https://www.mercadolibre.com.ar/consola-playstation-5-slim/p/MLA35000057",
    title: "Consola PlayStation 5 Slim",
    price: 999000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SONY",
    query: "playstation 5",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/joystick-dualsense-ps5-negro/p/MLA35000058",
    title: "Joystick DualSense PS5 Midnight Black",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SONY",
    query: "joystick ps5",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/silla-gamer-dxracer-formula-rgb-reclinable/p/MLA35000059",
    title: "Silla Gamer DXRacer Formula RGB Reclinable",
    price: 299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "DXRACER",
    query: "silla gamer rgb",
  },
  // CyberMonday Nov 2026 — audio
  {
    permalink: "https://www.mercadolibre.com.ar/parlante-portatil-jbl-charge-5/p/MLA35000060",
    title: "Parlante Portátil JBL Charge 5 Bluetooth",
    price: 149000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "JBL",
    query: "jbl parlante",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/auriculares-gaming-hyperx-cloud-iii/p/MLA35000061",
    title: "Auriculares Gaming HyperX Cloud III",
    price: 129000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "HYPERX",
    query: "headset gamer",
  },
  // CyberMonday Nov 2026 — computación
  {
    permalink: "https://www.mercadolibre.com.ar/computadora-de-escritorio-ryzen-5-16gb-512ssd/p/MLA35000062",
    title: "Computadora de Escritorio Ryzen 5 5600G 16GB 512GB SSD",
    price: 699000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "computadora de escritorio",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/teclado-gaming-redragon-kumara-rgb/p/MLA35000063",
    title: "Teclado Gaming Redragon Kumara RGB Mecánico",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "REDRAGON",
    query: "teclado gaming",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/mouse-inalambrico-logitech-mx-master-3s/p/MLA35000064",
    title: "Mouse Inalámbrico Logitech MX Master 3S",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LOGITECH",
    query: "mouse inalambrico",
  },
  // CyberMonday Nov 2026 — línea blanca
  {
    permalink: "https://www.mercadolibre.com.ar/ventilador-portatil-split-aire-movil/p/MLA35000065",
    title: "Ventilador Portátil Split Aire Móvil 12000 BTU",
    price: 299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "ventilador split",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/aire-portatil-hisense-12000-btu/p/MLA35000066",
    title: "Aire Portátil Hisense 12000 BTU",
    price: 349000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "HISENSE",
    query: "aire portatil",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/heladera-no-frost-samsung-415l/p/MLA35000067",
    title: "Heladera No Frost Samsung 415L Twin Cooling",
    price: 799000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "heladera no frost",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/lavarropas-inverter-lg-9kg-ai-direct-drive/p/MLA35000068",
    title: "Lavarropas Inverter LG 9KG AI Direct Drive",
    price: 699000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "LG ARGENTINA",
    query: "lavarropas inverter",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/microondas-con-grill-samsung-28l/p/MLA35000069",
    title: "Microondas con Grill Samsung 28L 900W",
    price: 149000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "microondas con grill",
  },
  // CyberMonday Nov 2026 — movilidad y outdoor
  {
    permalink: "https://www.mercadolibre.com.ar/bicicleta-mtb-rodado-29-21-velocidades/p/MLA35000070",
    title: "Bicicleta MTB Rodado 29 Aluminio 21 Velocidades",
    price: 299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "bicicleta mtb",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/mochila-notebook-samsonite-17-pulgadas/p/MLA35000071",
    title: "Mochila para Notebook Samsonite 17\" Guardit",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSONITE",
    query: "mochila notebook",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/camara-accion-gopro-hero13-black/p/MLA35000072",
    title: "Cámara de Acción GoPro HERO13 Black",
    price: 549000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "GOPRO",
    query: "cámara acción",
  },
  // CyberMonday Nov 2026 — smart home/IoT
  {
    permalink: "https://www.mercadolibre.com.ar/strip-led-inteligente-philips-hue-2m/p/MLA35000073",
    title: "Strip LED Inteligente Philips Hue 2m",
    price: 39999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PHILIPS",
    query: "strip led inteligente",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/termostato-inteligente-wifi-google-nest/p/MLA35000074",
    title: "Termostato Inteligente WiFi Google Nest",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "GOOGLE",
    query: "termostato inteligente",
  },
  // Música / instrumentos
  {
    permalink: "https://www.mercadolibre.com.ar/guitarra-electrica-fender-squier-stratocaster/p/MLA35000075",
    title: "Guitarra Eléctrica Fender Squier Stratocaster",
    price: 299000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "FENDER",
    query: "guitarra electrica",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/teclado-piano-yamaha-p45-88-teclas/p/MLA35000076",
    title: "Teclado Piano Yamaha P-45 88 Teclas",
    price: 399000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "YAMAHA",
    query: "teclado piano",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/auriculares-estudio-audio-technica-ath-m50x/p/MLA35000077",
    title: "Auriculares de Estudio Audio-Technica ATH-M50x",
    price: 199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "AUDIO-TECHNICA",
    query: "auriculares estudio",
  },
  // Jardín / exterior / piscina
  {
    permalink: "https://www.mercadolibre.com.ar/pileta-inflable-intex-bestway-305x183cm/p/MLA35000078",
    title: "Pileta Inflable Intex Rectangular 305x183x56cm",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "INTEX",
    query: "pileta inflable",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/silla-de-jardin-plastica-plastico-apilable/p/MLA35000079",
    title: "Silla de Jardín Plástica Apilable",
    price: 14999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "silla de jardin",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/parrilla-electrica-2000w-tefal/p/MLA35000080",
    title: "Parrilla Eléctrica Tefal 2000W",
    price: 89999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TEFAL",
    query: "parrilla electrica",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/asador-a-gas-horizontal-4-hornallas/p/MLA35000081",
    title: "Asador a Gas Horizontal 4 Hornallas",
    price: 199000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "asador a gas",
  },
  // Material escolar / oficina
  {
    permalink: "https://www.mercadolibre.com.ar/mochila-escolar-primaria-totto-16-pulgadas/p/MLA35000082",
    title: "Mochila Escolar Primaria Totto 16\"",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TOTTO",
    query: "mochila escolar",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/lapicera-parker-jotter-acero/p/MLA35000083",
    title: "Lapicera Parker Jotter Acero Inoxidable",
    price: 19999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "PARKER",
    query: "lapicera parker",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/calculadora-cientifica-casio-fx-991la-cw/p/MLA35000084",
    title: "Calculadora Científica Casio FX-991LA CW",
    price: 24999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "CASIO",
    query: "calculadora cientifica",
  },
  // Repuestos y accesorios celular
  {
    permalink: "https://www.mercadolibre.com.ar/bateria-repuesto-samsung-galaxy-a54-5000mah/p/MLA35000085",
    title: "Batería Repuesto Samsung Galaxy A54 5000mAh",
    price: 14999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "bateria celular repuesto",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/pantalla-samsung-galaxy-a53-original/p/MLA35000086",
    title: "Pantalla Original Samsung Galaxy A53 Con Marco",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "pantalla celular",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/auriculares-tipo-c-samsung-akg/p/MLA35000087",
    title: "Auriculares Tipo C Samsung AKG In-Ear",
    price: 9999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSUNG ARGENTINA",
    query: "auriculares tipo c",
  },
  // Salud / bienestar
  {
    permalink: "https://www.mercadolibre.com.ar/tensíometro-digital-de-brazo-omron-m3/p/MLA35000088",
    title: "Tensiómetro Digital de Brazo Omron M3",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "OMRON",
    query: "tensiómetro digital",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/oximetro-de-pulso-digital-beurer/p/MLA35000089",
    title: "Oxímetro de Pulso Digital Beurer PO30",
    price: 19999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BEURER",
    query: "oximetro",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/bascula-digital-beurer-gs-300-180kg/p/MLA35000090",
    title: "Báscula Digital Beurer GS300 180kg Vidrio",
    price: 24999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BEURER",
    query: "bascula digital",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/masajeador-electrico-de-cuello-y-espalda/p/MLA35000091",
    title: "Masajeador Eléctrico de Cuello y Espalda Shiatsu",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "masajeador electrico",
  },
  // Cocina / vajilla
  {
    permalink: "https://www.mercadolibre.com.ar/olla-a-presion-tramontina-4-5l-acero/p/MLA35000092",
    title: "Olla a Presión Tramontina 4.5L Acero Inoxidable",
    price: 49999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TRAMONTINA",
    query: "olla a presion",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/set-cuchillos-tramontina-8-piezas-acero/p/MLA35000093",
    title: "Set Cuchillos Tramontina 8 Piezas Acero Inoxidable",
    price: 39999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "TRAMONTINA",
    query: "set cuchillos",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/tabla-de-picar-bambu-45x30cm/p/MLA35000094",
    title: "Tabla de Picar Bambú 45x30cm",
    price: 12999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "tabla de picar",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/juego-de-vasos-bormioli-rocco-12-piezas/p/MLA35000095",
    title: "Juego de Vasos Bormioli Rocco 12 Piezas",
    price: 24999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "BORMIOLI ROCCO",
    query: "juego de vasos",
  },
  // Bebés adicional
  {
    permalink: "https://www.mercadolibre.com.ar/monitor-bebe-wifi-video-motorola-vm65/p/MLA35000096",
    title: "Monitor Bebé WiFi Video Motorola VM65",
    price: 79999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "MOTOROLA",
    query: "monitor bebe wifi",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/silla-booster-bebe-fisher-price-hasta-18kg/p/MLA35000097",
    title: "Silla Booster Bebé Fisher-Price Hasta 18kg",
    price: 34999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "FISHER-PRICE",
    query: "silla booster bebe",
  },
  // Viaje / turismo
  {
    permalink: "https://www.mercadolibre.com.ar/maleta-de-viaje-samsonite-68cm-spinner/p/MLA35000098",
    title: "Maleta de Viaje Samsonite 68cm Spinner",
    price: 149000,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: "SAMSONITE",
    query: "maleta de viaje",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/candado-tsa-magnum-combinacion-4-digitos/p/MLA35000099",
    title: "Candado TSA Magnum Combinación 4 Dígitos",
    price: 9999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "candado tsa",
  },
  {
    permalink: "https://www.mercadolibre.com.ar/almohada-de-viaje-cervical-memory-foam/p/MLA35000100",
    title: "Almohada de Viaje Cervical Memory Foam",
    price: 14999,
    currency_id: "ARS",
    thumbnail: null,
    seller_nickname: null,
    query: "almohada de viaje",
  },
];
